config/routes.rb
Indiatech::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions =>  'users/sessions'}

  get "home/index"

  resources :users, :only => [:update]

  get 'users/goodies/:type', as: :goodies, to: 'users#goodies'
  get 'dashboard', as: :user_root, to: 'users#dashboard'
  get 'lazy_dashboard', :as => :lazy_dashboard, to: 'users#lazy_dashboard'
  get 'feed', :as => :feed, to: 'feeds#feed'
  get 'feed/links', :as => :link_feed, to: 'feeds#links'
  get 'feed/cards', :as => :card_feed, to: 'feeds#cards'
  get 'feed/micros', :as => :micro_feed, to: 'feeds#micros'
  get 'feed/all', :as => :all_feed, to: 'feeds#cards_links_micros'
  get "users/share", :as => :share, to: 'users#share'

  get "notifications", :as => :notifications, to: 'notifications#notifications'
  resources :notifications, only: [:destroy] do
    member do
      post :mark_read
    end
  end
  resources :micros, only: [:create, :show]
  resources :cards, only: [:create, :show]
  resources :photos, :only => [:create, :update, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :high_fives, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :link_categories, only: [:create, :destroy]

  get ':username/followers', :to => 'users#followers', :as => :user_followers
  get ':username/followings', :to => 'users#followers', :as => :user_followings
  get '/followers', :to => 'users#followers', :as => :followers
  get '/followings', :to => 'users#followings', :as => :followings
  get ':username/project/add', :to => 'users#add_project', :as => :user_add_project, :constraints => { :username => /[A-Za-z0-9_]+/} 
  get ':username/company/add', :to => 'users#add_company', :as => :user_add_company, :constraints => { :username => /[A-Za-z0-9_]+/}

  get ':username', :to => 'users#profile', :as => :user_profile, :constraints => lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }
  get ':username/edit', :to => 'users#edit', :as => :user_edit, :constraints =>  lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }

  root :to => 'home#index'

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

	before_filter :authenticate_user!, :only => [:feed]

	def feed
    @user = current_user
    get_feeds
  end

  def links
  	get_feeds("Link")
  end

  def cards
  	get_feeds("Card")
  end

  def micros
  	get_feeds("Micro")
  end

  def cards_links_micros
  	links
  	cards
  	micros
  end

  private

  def get_feeds(type=nil)
  	if !request.xhr?
      feeds = current_user.page_activities_oj(current_user.followed_pool.values, params[:page] || 1, 5, type)[0].html_safe
    else
      feeds, total_pages = current_user.page_activities_oj(current_user.followed_pool.values, params[:page] || 1, 5, type)
      feeds = feeds.html_safe
    end
    case type
    when "Link"
    	@link_feed = feeds
      @link_total_pages = total_pages
    when "Card"
    	@card_feed = feeds
      @card_total_pages = total_pages
    when "Micro"
    	@micro_feed = feeds
      @micro_total_pages = total_pages
    else
    	@feeds = feeds
      @total_pages = total_pages
    end   	
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/cards.js.erb
var card_feed_temp = _.template($("#feed-under-template").html());
var card_feeds = JSON.parse('<%= escape_javascript @card_feed %>')
$("#mycardsTab #feed-dashboard").append(card_feed_temp({activities: card_feeds}));
$("abbr.timeago").timeago();
<% if @card_total_pages > params[:page].to_i %>
$("#mycardsTab #load_more_feed").attr('href', '<%= card_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2) %>')
<% else %>
$("#mycardsTab #load_more_feed").remove();
<% end %>

app/views/feeds/cards_links_micros.js.erb
var card_feed_temp = _.template($("#feed-under-template").html());
var card_feeds = JSON.parse('<%= escape_javascript @card_feed %>')
$("#mycardsTab #feed-dashboard").append(card_feed_temp({activities: card_feeds}));
$("abbr.timeago").timeago();
<% if @card_total_pages > params[:page].to_i %>
$("#mycardsTab #load_more_feed").attr('href', '<%= card_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2) %>')
<% else %>
$("#mycardsTab#load_more_feed").remove();
<% end %>

var link_feed_temp = _.template($("#feed-under-template").html());
var link_feeds = JSON.parse('<%= escape_javascript @link_feed %>')
$("#mylinksTab #feed-dashboard").append(link_feed_temp({activities: link_feeds}));
$("abbr.timeago").timeago();
<% if @link_total_pages > params[:page].to_i %>
$("#mylinksTab #load_more_feed").attr('href', '<%= link_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2) %>')
<% else %>
$("#mylinksTab #load_more_feed").remove();
<% end %>


var micro_feed_temp = _.template($("#feed-under-template").html());
var micro_feeds = JSON.parse('<%= escape_javascript @micro_feed %>')
$("#mymicrosTab #feed-dashboard").append(micro_feed_temp({activities: micro_feeds}));
$("abbr.timeago").timeago();
<% if @micro_total_pages > params[:page].to_i %>
$("#mymicrosTab #load_more_feed").attr('href', '<%= micro_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2) %>')
<% else %>
$("#mymicrosTab #load_more_feed").remove();
<% end %>

app/views/feeds/feed.html.erb
<%= content_for :js do %>
<%= render "users/dashboard_templates.html.erb" %>
<script type="text/javascript" charset="utf-8">
  var feeds = JSON.parse('<%= escape_javascript @feeds %>')
</script>
<% end %>
<div class="twelve columns centered landing-container">
  <div class="row">
    <%= render "users/sidebar_dashboard" %>
    <div class="six columns">
      <div class="row">
        <div class="twelve columns">
          <div class="row">
            <div class="nine columns push-three" style="padding: 0px;">
              <dl class="dashboard tabs">
                <dd class="active"><a href="#myfeed">Feed</a></dd>
                <dd><a href="#mylinks">Links</a></dd>
                <dd><a href="#mymicros">Micros</a></dd>
                <dd><a href="#mycards">Cards</a></dd>
              </dl>
            </div>
         </div>
          <ul class="tabs-content">
            <li class="active" id="myfeedTab">
              <div id="feed-dashboard">
              </div>
              <%= link_to "Load More", feed_path(:page => 2), :remote => true, :disable_with => "Loading..", :id => "load_more_feed" %>
            </li>

            <li id="mylinksTab">
              <div id="feed-dashboard">
              </div>
              <%= link_to "Load More", link_feed_path(:page => 2), :remote => true, :disable_with => "Loading..", :id => "load_more_feed" %>
            </li>

            <li id="mymicrosTab">
              <div id="feed-dashboard">
              </div>
              <%= link_to "Load More", micro_feed_path(:page => 2), :remote => true, :disable_with => "Loading..", :id => "load_more_feed" %>
            </li>

            <li id="mycardsTab">
              <div id="feed-dashboard">
              </div>
              <%= link_to "Load More", card_feed_path(:page => 2), :remote => true, :disable_with => "Loading..", :id => "load_more_feed" %>
            </li>
          </ul>
        </div>
      </div>     
    </div>
    <div class="three columns">
    </div>
  </div>
</div>

app/views/feeds/feed.js.erb
var feed_temp = _.template($("#feed-under-template").html());
var feeds = JSON.parse('<%= escape_javascript @feeds %>')
$("#myfeedTab #feed-dashboard").append(feed_temp({activities: feeds}));
$("abbr.timeago").timeago();
<% if @total_pages > params[:page].to_i %>
$("#myfeedTab #load_more_feed").attr('href', '<%= feed_path(:page => params[:page].to_i + 1) %>')
<% else %>
$("#myfeedTab #load_more_feed").remove();
<% end %>

app/views/feeds/links.js.erb
var link_feed_temp = _.template($("#feed-under-template").html());
var link_feeds = JSON.parse('<%= escape_javascript @link_feed %>')
$("#mylinksTab #feed-dashboard").append(link_feed_temp({activities: link_feeds}));
$("abbr.timeago").timeago();
<% if @link_total_pages > params[:page].to_i %>
$("#mylinksTab #load_more_feed").attr('href', '<%= link_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2 ) %>')
<% else %>
$("#mylinksTab #load_more_feed").remove();
<% end %>

app/views/feeds/micros.js.erb
var micro_feed_temp = _.template($("#feed-under-template").html());
var micro_feeds = JSON.parse('<%= escape_javascript @micro_feed %>')
$("#mymicrosTab #feed-dashboard").append(micro_feed_temp({activities: micro_feeds}));
$("abbr.timeago").timeago();
<% if @micro_total_pages > params[:page].to_i %>
$("#mymicrosTab #load_more_feed").attr('href', '<%= micro_feed_path(:page => params[:page] ? params[:page].to_i + 1 : 2 ) %>')
<% else %>
$("#mymicrosTab #load_more_feed").remove();
<% end %>