config/routes.rb
Indiatech::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions =>  'users/sessions'}

  get "home/index"

  resources :users, :only => [:update]

  get 'users/goodies/:type', as: :goodies, to: 'users#goodies'
  get 'dashboard', as: :user_root, to: 'users#dashboard'
  get 'lazy_dashboard', :as => :lazy_dashboard, to: 'users#lazy_dashboard'
  get 'feed', :as => :feed, to: 'feeds#feed'
  get 'feed/links', :as => :link_feed, to: 'feeds#links'
  get 'feed/cards', :as => :card_feed, to: 'feeds#cards'
  get 'feed/micros', :as => :micro_feed, to: 'feeds#micros'
  get 'feed/all', :as => :all_feed, to: 'feeds#cards_links_micros'
  get "users/share", :as => :share, to: 'users#share'

  get "notifications", :as => :notifications, to: 'notifications#notifications'
  resources :notifications, only: [:destroy] do
    member do
      post :mark_read
    end
  end
  resources :micros, only: [:create, :show]
  resources :cards, only: [:create, :show]
  resources :photos, :only => [:create, :update, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :high_fives, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :link_categories, only: [:create, :destroy]

  get ':username/followers', :to => 'users#followers', :as => :user_followers
  get ':username/followings', :to => 'users#followers', :as => :user_followings
  get '/followers', :to => 'users#followers', :as => :followers
  get '/followings', :to => 'users#followings', :as => :followings
  get ':username/project/add', :to => 'users#add_project', :as => :user_add_project, :constraints => { :username => /[A-Za-z0-9_]+/} 
  get ':username/company/add', :to => 'users#add_company', :as => :user_add_company, :constraints => { :username => /[A-Za-z0-9_]+/}

  get ':username', :to => 'users#profile', :as => :user_profile, :constraints => lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }
  get ':username/edit', :to => 'users#edit', :as => :user_edit, :constraints =>  lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }

  root :to => 'home#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  attr_accessible :closed_at, :key, :position, :viewed_at,  :actor, :user, :resource

  scope :unread, -> { where viewed_at: nil }
  default_scope order: 'notifications.created_at DESC'

  belongs_to :user
  belongs_to :actor, class_name: "User"
  belongs_to :resource, :polymorphic => true

  def text(params = {})
    # TODO: some helper for key transformation for two supported formats
    k = key.split('.')
    k.unshift('notification') if k.first != 'notification'
    k = k.join('.')

    (I18n.t(k, {}) + "<a href='#{self.resource.slug_path}'> #{self.resource_type.downcase} </a>").html_safe
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	before_filter :authenticate_user!
	before_filter :find_notification, :only => [:mark_read, :destroy]

  def notifications
  	@notifications = 	current_user.notifications.paginate(:page => 1, :per_page => 30).includes([:actor])
  	render "index"
  end

  def mark_read
  	@notification.update_attribute("viewd_at", Time.zone.now)
  end

  def destroy
  	@notification.destroy
  end

  private

  def find_notification
  	@notification = Notification.where(params[:id]).first
  	render :status => 404 and return unless @notification
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<div class="twelve columns left-border" id="noti_<%= notification.id %>">

  <div class="title date">
    <span class="invisible">
      x
    </span>
  </div>

  <div class="panel notification">
    <%= link_to "x", notification_path(notification), :class => "close grey", :method => "delete", :remote => true %>
    <div class="content head-font head-color">
      <span>
      <a href="<%= user_path(notification.actor) %>"><%= "@" + notification.actor.username %></a>
    </span>
    <%= notification.text %>
    <abbr class="grey timeago" title="<%= notification.created_at.iso8601 %>"></abbr>
    </div>
  </div>
</div>

app/views/notifications/destroy.js.erb
$("#noti_<%= @notification.id %>").remove()

app/views/notifications/index.html.erb
<div class="twelve columns centered landing-container">
  <div class="row">
    <%= render "users/sidebar_dashboard" %>
    <div class="six columns" style="padding-top: 26px;margin-bottom: 25px;">
      <h2>Notifications:</h2> 
      <div class="row card-container">
        <% if @notifications[0] %>
          <%= render :partial => 'notification', :collection => @notifications %>
        <% else %>
          <div class="twelve columns left-border">
            <div class="panel notification">
              <div class="content head-font head-color">              
                No Notifications
              </div>
            </div>
          </div>
        <% end %>
      </div>        
    </div>
    <div class="three columns">
    </div>
  </div>
</div>

app/views/notifications/mark_closed.js.erb
$("#noti_<%= @notification.id %>").add_class("viewed")