config/routes.rb
Indiatech::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations", :sessions =>  'users/sessions'}

  get "home/index"

  resources :users, :only => [:update]

  get 'users/goodies/:type', as: :goodies, to: 'users#goodies'
  get 'dashboard', as: :user_root, to: 'users#dashboard'
  get 'lazy_dashboard', :as => :lazy_dashboard, to: 'users#lazy_dashboard'
  get 'feed', :as => :feed, to: 'feeds#feed'
  get 'feed/links', :as => :link_feed, to: 'feeds#links'
  get 'feed/cards', :as => :card_feed, to: 'feeds#cards'
  get 'feed/micros', :as => :micro_feed, to: 'feeds#micros'
  get 'feed/all', :as => :all_feed, to: 'feeds#cards_links_micros'
  get "users/share", :as => :share, to: 'users#share'

  get "notifications", :as => :notifications, to: 'notifications#notifications'
  resources :notifications, only: [:destroy] do
    member do
      post :mark_read
    end
  end
  resources :micros, only: [:create, :show]
  resources :cards, only: [:create, :show]
  resources :photos, :only => [:create, :update, :destroy]

  resources :relationships, only: [:create, :destroy]
  resources :high_fives, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :link_categories, only: [:create, :destroy]

  get ':username/followers', :to => 'users#followers', :as => :user_followers
  get ':username/followings', :to => 'users#followers', :as => :user_followings
  get '/followers', :to => 'users#followers', :as => :followers
  get '/followings', :to => 'users#followings', :as => :followings
  get ':username/project/add', :to => 'users#add_project', :as => :user_add_project, :constraints => { :username => /[A-Za-z0-9_]+/} 
  get ':username/company/add', :to => 'users#add_company', :as => :user_add_company, :constraints => { :username => /[A-Za-z0-9_]+/}

  get ':username', :to => 'users#profile', :as => :user_profile, :constraints => lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }
  get ':username/edit', :to => 'users#edit', :as => :user_edit, :constraints =>  lambda{|req| 
                                                                                         req[:username].match(/[A-Za-z0-9_]+/) && req[:username] != 'dashboard' && req[:username] != "lazy_dashboard" && req[:username] != "feed"
                                                                                       }

  root :to => 'home#index'

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	before_filter :set_or_create_current_user

	def linkedin
		render "/home/index"
	end

	def github
		render "/home/index"
	end

	private

	def set_or_create_current_user
		omniauth = request.env["omniauth.auth"]
		authentication = Authentication.find_by_provider_and_uid(Authentication::PROVIDER[omniauth[:provider]], omniauth[:uid])
		if authentication
			@user = authentication.user
			sign_in @user
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => omniauth[:provider]
			redirect_to user_path(@user)
		elsif current_user
			current_user.authentication.create(:uid => omniauth[:uid], :provider => Authentication::PROVIDER[omniauth[:provider]])
			flash[:notice] = "Authentication successfull."
			redirect_to user_path(@user)
		else
			@user = User.new(:email => omniauth[:info][:email], :first_name => omniauth[:info][:first_name], :last_name => omniauth[:info][:last_name])
			session[:omniauth] = omniauth.except('extra')
			render "users/registrations/new"
		end
	end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::SessionsController

	prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]

  # GET /resource/sign_up
  def new
    resource = build_resource({})
    respond_with resource
  end

  # POST /resource
  def create
    build_resource
    if session[:omniauth]
    	@user.authentications = [Authentication.new(:uid => session[:omniauth].uid, :provider => Authentication::PROVIDER[session[:omniauth].provider], :first_name => session[:omniauth].info.first_name, :last_name => session[:omniauth].info.last_name, :access_token =>  session[:omniauth].credentials.token, :profile => session[:omniauth].info.urls.GitHub, :image => session[:omniauth].info.image )] if session[:omniauth].provider == "github"
    	@user.authentications = [Authentication.new(:uid => session[:omniauth].uid, :provider => Authentication::PROVIDER[session[:omniauth].provider], :first_name => session[:omniauth].info.first_name, :last_name => session[:omniauth].info.last_name, :access_token =>  session[:omniauth].credentials.token, :secret => session[:omniauth].credentials.secret, :profile => session[:omniauth].info.urls.public_profile, :image => session[:omniauth].info.image )] if session[:omniauth].provider == "linkedin"
  	end
    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_up(resource_name, resource)
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # GET /resource/edit
  def edit
    render :edit
  end

  # PUT /resource
  # We need to use a copy of the resource because we don't want to change
  # the current user in place.
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    if resource.update_with_password(resource_params)
      if is_navigational_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      respond_with resource, :location => after_update_path_for(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  # DELETE /resource
  def destroy
    resource.destroy
    Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
    set_flash_message :notice, :destroyed if is_navigational_format?
    respond_with_navigational(resource){ redirect_to after_sign_out_path_for(resource_name) }
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    expire_session_data_after_sign_in!
    redirect_to new_registration_path(resource_name)
  end

  protected

  def create_social_authentication
  end

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
      resource.pending_reconfirmation? &&
      previous != resource.unconfirmed_email
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    hash ||= resource_params || {}
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    user_edit_path(:username => current_user.username)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    respond_to?(:root_path) ? root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", :force => true)
    self.resource = send(:"current_#{resource_name}")
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < DeviseController
  prepend_before_filter :require_no_authentication, :only => [ :new, :create ]
  prepend_before_filter :allow_params_authentication!, :only => :create
  prepend_before_filter { request.env["devise.skip_timeout"] = true }

  # GET /resource/sign_in
  def new
    resource = build_resource(nil, :unsafe => true)
    clean_up_passwords(resource)
    respond_with(resource, serialize_options(resource))
  end

  # POST /resource/sign_in
  def create
    resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    respond_with resource, :location => after_sign_in_path_for(resource)
  end

  # DELETE /resource/sign_out
  def destroy
    redirect_path = after_sign_out_path_for(resource_name)
    signed_out = (Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name))
    set_flash_message :notice, :signed_out if signed_out

    # We actually need to hardcode this as Rails default responder doesn't
    # support returning empty response on GET request
    respond_to do |format|
      format.any(*navigational_formats) { redirect_to redirect_path }
      format.all do
        head :no_content
      end
    end
  end

  protected

  def serialize_options(resource)
    methods = resource_class.authentication_keys.dup
    methods = methods.keys if methods.is_a?(Hash)
    methods << :password if resource.respond_to?(:password)
    { :methods => methods, :only => [:password] }
  end

  def auth_options
    { :scope => resource_name, :recall => "#{controller_path}#new" }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!, :only => [:edit,:share, :update,:add_company, :add_project, :dashboard, :lazy_dashboard, :feed]
	before_filter :find_user_by_username , :only => [:profile, :edit, :add_project,:add_company, :goodies]
  before_filter :find_username_or_authenticate, :only => [:followers, :followings]
  def profile
    @micros = @user.micros.paginate(:page => 1, :per_page => 10).includes(:high_fives)
    @links = @user.links.paginate(:page => 1, :per_page => 10).includes(:high_fives)
    @cards = @user.cards.paginate(:page => 1, :per_page => 10).includes(:high_fives)
  end

  def goodies
    if params[:type] == "micro"
      @micros = @user.micros.paginate(:page => params[:page] || 1, :per_page => 10).includes(:high_fives)
    elsif params[:type] == "link"
      @links = @user.links.paginate(:page =>  params[:page] || 1, :per_page => 10).includes(:high_fives)
    elsif params[:type] == "card"
      @cards = @user.cards.paginate(:page =>  params[:page] || 1, :per_page => 10).includes(:high_fives)
    end
  end

  def share
    @resource = params[:resource_type].constantize.where(:id => params[:track_id]).first
    if @resource
      @resource.activities.create({key: "#{params[:resource_type].downcase}.shared", user: current_user})
      @resource.user.notify("#{params[:resource_type].downcase}.shared", current_user, @resource)
    end
  end

  def dashboard
    @recent_notifications = current_user.notifications.unread.limit(10)
    @stats = {followers: current_user.followers_counter, followings: current_user.followed_counter}
  end

  def followers
    @followers = @user.followers.paginate(:per_page => 30, :page => params[:page] || 1).includes(:skills)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def followings
    @followings = @user.followed_users.paginate(:per_page => 30, :page => params[:page] || 1).includes(:skills)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def lazy_dashboard
    render :json => current_user.recent_activities_oj(current_user.follower_ids), :layout => false
  end

  def edit
    @user.schools.build if @user.schools.count == 0
    render 'edit_profile'
  end

  def add_project
    @user.projects.build if @user.projects.count == 0
    render 'update_project'
  end

  def add_company
    @user.company_user_profiles.build if @user.company_user_profiles.count == 0
    render 'update_company'
  end

  def update
  	current_user.update_attributes(params[:user])
  	redirect_to  user_root_path
  end

  protected
  	def find_user_by_username
  		@user = User.where(:username => params[:username]).first if params[:username]
  		redirect_to root_path, :error => "Could not find the user." unless @user
  	end

  	def user_is_current_user?
  		@user_is_current_user ||= (current_user == @user)
  	end

    def find_username_or_authenticate
      if params[:username]
        find_user_by_username
      else
        authenticate_user!
        @user = current_user
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_card.html.erb
<div class="twelve columns">
  <div class="panel card" id="card<%= card.id %>">
    <div class="content head-font head-color">
      <p style="font-weight: normal;margin-bottom:0px;"></p>
     <a href="<%= card_path(card) %>" ><%= card.description %></a>
      <p class="high-five-count-container"><span class="high-five-count"><%= card.high_fives.length %></span> High Fives &nbsp;&nbsp;<span class="view-count"><%= card.view_count %></span> Views</p>
    </div>

    <ul class="float-right-list action-list">
    <li class="high_five_but">
      <% if current_user %>
      <% unless card.high_fives.map(&:user_id).include?(current_user.id) %>
        <%= high_five_form(card.id, "Card", current_user.id) %>
      <% end %>
      <% else %>
        <%= link_to "high five!", "#", :class => "reveal-signin-modal", :"data-alert-msg" => "Please join to High Five!" %>
      <% end %>
    </li>

    <%= render :partial => "layouts/share", :locals => {:url => card_url(card), :description => card.description, :title => "#{card.user.full_name} created a Card at WeAreIndiaTech", :type => "Card", :track_id => card.id} %>
  </ul>
  </div>
</div>

app/views/users/_dashboard_templates.html.erb
<script type="text/template" id="feed-under-template">
		<div class="row">
			<div class="columns twelve">
				<%% _(activities).each(function (activity, i) { %>
					<div class="row card-container">
						<div class="columns one">
			        
						</div>
						<div class="columns eleven" style="margin: 0px; padding: 0px; border-left: 4px solid #E2E5E7">
							<div class="title date">
			        	<a herf="<%%= activity.user.profile_url %>" class="card-avatar square small">
				          <img alt="gravatar <%%= activity.user.name %>" src="<%%= Gravtastic(activity.user.email, {default: 'identicon', size: 90}) %>">
			          </a>
								<span>
									<a href="<%%= activity.user.profile_url %>"><%%= activity.user.name %></a>
								</span>
								<%%= activity.title %>
								<abbr class="grey timeago" title="<%%= activity.hours_ago %>"></abbr>
							</div>

								<%% if(activity.trackable_type == 'Micro') { %>
									<div class="row no-margin-row">
										<%= render "users/micro_dashboard_template" %>
									</div>
								<%% } else if(activity.trackable_type == 'Card'){ %>
									<div class="row no-margin-row">
										<%= render "users/card_dashboard_template" %>
									</div>
								<%% } else if(activity.trackable_type == 'Link'){ %>
									<div class="row no-margin-row">
										<%= render "users/link_dashboard_template" %>
									</div>
								<%% }  %>
						</div>
					</div>
				<%% }) %>
			</div>
		</div>
</script>

app/views/users/_follower.html.erb
<div class="row card-container">
	<div class="columns one"></div>
	<div class="columns eleven left-border" style="margin: 0px;">
		<div class="title date">
    	<a herf="<%= user_profile_path(follower.username) %>" class="card-avatar square small">
      	<img alt="gravatar <%= follower.username %>" src="<%= follower.gravatar_url(default: 'identicon', size: 90) %>">
    	</a>
			<span class="invisible">
				x
			</span>
		</div>			
		<div class="row no-margin-row">
			<div class="twelve columns">
				<div class="panel micro" id="micro785">
			    <div class="content head-font head-color">
			      <p class="m-bottom0">
			      	<%= link_to follower.format_username, user_profile_path(follower.username), class: "grey"  %>
			      </p>
			      <%= link_to follower.full_name, user_profile_path(follower.username) %><br />
			      <span style="font-size: 19px;"><%= follower.title %></span>
			      <p class="grey"><span><%= follower.followers_counter %></span> Followers&nbsp;&nbsp;<span class="view-count"><%= follower.followed_counter %></span> Followings &nbsp;&nbsp;<span><%= follower.cards_counter %></span> Cards</p>
			    </div>
			    <article>
		        <dl class="sub-nav skill-list">
		          <dt class="m-bottom0">Skills:</dt>
		          <% follower.skills.each do |skill| %>
		            <dd><a href="#" class="button small tag"><%= skill.name %></a></dd>
		          <% end %>
		        </dl>
    			</article>
			    <div id="follow-but<%= follower.id %>" class="corner">
		        <% if current_user && current_user != follower %>
		          <% if current_user.following?(follower)%>
		            <%= render :partial => 'unfollow', :locals => {:user => follower} %>
		          <% else %>
		            <%= render :partial => 'follow', :locals => {:user => follower} %>
		          <% end %>
		        <% else %>
		          <%= render :partial => 'follow', :locals => {:user => follower} %>
		        <% end %>
      		</div>
				</div>
			</div>
		</div>				
	</div>
</div>

app/views/users/_following.html.erb
<div class="row card-container">
	<div class="columns one"></div>
	<div class="columns eleven left-border" style="margin: 0px;">
		<div class="title date">
    	<a herf="<%= user_profile_path(following.username) %>" class="card-avatar square small">
      	<img alt="gravatar <%= following.username %>" src="<%= following.gravatar_url(default: 'identicon', size: 90) %>">
    	</a>
			<span class="invisible">
				x
			</span>
		</div>			
		<div class="row no-margin-row">
			<div class="twelve columns">
				<div class="panel micro" id="micro785">
			    <div class="content head-font head-color">
			      <p class="m-bottom0">
			      	<%= link_to following.format_username, user_profile_path(following.username), class: "grey"  %>
			      </p>
			      <%= link_to following.full_name, user_profile_path(following.username) %><br />
			      <span style="font-size: 19px;"><%= following.title %></span>
			      <p class="grey"><span><%= following.followers_counter %></span> Followers&nbsp;&nbsp;<span class="view-count"><%= following.followed_counter %></span> Followings &nbsp;&nbsp;<span><%= following.cards_counter %></span> Cards</p>
			    </div>
			    <article>
		        <dl class="sub-nav skill-list">
		          <dt class="m-bottom0">Skills:</dt>
		          <% following.skills.each do |skill| %>
		            <dd><a href="#" class="button small tag"><%= skill.name %></a></dd>
		          <% end %>
		        </dl>
    			</article>
			    <div id="follow-but<%= following.id %>" class="corner">
		        <% if current_user && current_user != following %>
		          <% if current_user.following?(following)%>
		            <%= render :partial => 'unfollow', :locals => {:user => following} %>
		          <% else %>
		            <%= render :partial => 'follow', :locals => {:user => following} %>
		          <% end %>
		        <% else %>
		          <%= render :partial => 'follow', :locals => {:user => following} %>
		        <% end %>
      		</div>
				</div>
			</div>
		</div>				
	</div>
</div>

app/views/users/_high_five_destroy.html.erb
<%= form_for(@high_five, html: { method: :delete, style: "margin: 0px"}, remote: true) do |f| %>
  <%= f.submit "unhigh five!", style: "border: none; background: #F2F2F2;" %>
<% end %>

app/views/users/_link_dashboard_template.html.erb
<div class="twelve columns">
  <div class="panel link" id="link<%%= activity.trackable.id %>">
    <div class="content head-font head-color">
      <p style="font-weight: normal;margin-bottom:0px;"><a class="grey" href="<%%= activity.user.profile_url %>">@<%%= activity.user.username %></a></p>
      <a href="<%%= activity.trackable.url %>" target="_blank"><%%= activity.trackable.content %></a>
      <p class="high-five-count-container"><span class="high-five-count"><%%= activity.trackable.high_fives_length %></span> High Fives&nbsp;&nbsp;<span class="view-count"><%%= activity.trackable.view_count %></span> Views</p>
    </div>
    <ul class="float-right-list action-list">
      <li class="high_five_but">
        <% if current_user %>
        <%% if(!activity.trackable.high_fived)  {%>
        <form accept-charset="UTF-8" action="/high_fives" class="new_high_five" data-remote="true" id="new_high_five" method="post" style="margin: 0px">
            <input id="high_five_resource_id" name="high_five[resource_id]" type="hidden" value="<%%= activity.trackable.id %>">
            <input id="high_five_resource_type" name="high_five[resource_type]" type="hidden" value="Link">
            <input id="high_five_user_id" name="high_five[user_id]" type="hidden" value="<%= current_user.id %>">
            <input class="small button tag" data-disable-with = "wait" name="commit" type="submit" value="high five!">
        </form>
        <%% } %>
        <% else %>
          <%= link_to "high five!", "#", :class => "reveal-signin-modal", :"data-alert-msg" => "Please join to High Five!" %>
        <% end %>
      </li>

      <li>
        <%= link_to "share", "", :class => "small button tag" %>
      </li>
    </ul>
  </div>
</div>

app/views/users/_micro.html.erb
<div class="twelve columns">
  <div class="panel micro" id="micro<%= micro.id %>">
    <div class="content head-font head-color">
      <p style="font-weight: normal;margin-bottom:0px;"></p>
      <a href="<%= micro_path(micro) %>"><%= micro.content %></a>
      <p class="high-five-count-container"><span class="high-five-count"><%= micro.high_fives.length %></span> High Fives&nbsp;&nbsp;<span class="view-count"><%= micro.view_count %></span> Views &nbsp;&nbsp;<span class="view-count"><%= micro.replies.length %></span> Replies</p>
    </div>
    <ul class="float-right-list action-list social">
      <li class="high_five_but">
        <% if current_user %>
          <% unless micro.high_fives.map(&:user_id).include?(current_user.id) %>
            <%= high_five_form(micro.id, "Micro", current_user.id) %>
          <% end %>
        <% else %>
          <%= link_to "high five!", "#", :class => "reveal-signin-modal", :"data-alert-msg" => "Please join to High Five!" %>
        <% end %>
      </li>

      <%= render :partial => "layouts/share", :locals => {:url => micro_url(micro), :description => micro.content, :title => "#{micro.user.full_name} created a Micro at WeAreIndiaTech", :type => "Micro", :track_id => micro.id} %>

      <li>
        <%= link_to "reply", micro_path(micro), :class => "small button tag" %>
      </li>
    </ul>
  </div>
</div>

app/views/users/_micro_dashboard_template.html.erb
<div class="twelve columns">
  <div class="panel micro" id="micro<%%= activity.trackable.id %>">
    <div class="content head-font head-color">
      <p style="font-weight: normal;margin-bottom:0px;"><a class="grey" href="<%%= activity.user.profile_url %>">@<%%= activity.user.username %></a></p>
      <a herf="<%%= activity.trackable.url %>"><%%= activity.trackable.content %></a>
      <p class="high-five-count-container"><span class="high-five-count"><%%= activity.trackable.high_fives_length %></span> High Fives&nbsp;&nbsp;<span class="view-count"><%%= activity.trackable.view_count %></span> Views &nbsp;&nbsp;<span class="view-count"><%%= activity.trackable.replies_count %></span> Replies</p>
    </div>
    <ul class="float-right-list action-list">
      <li class="high_five_but">
        <% if current_user %>
        <%% if(!activity.trackable.high_fived)  {%>
        <form accept-charset="UTF-8" action="/high_fives" class="new_high_five" data-remote="true" id="new_high_five" method="post" style="margin: 0px">
            <input id="high_five_resource_id" name="high_five[resource_id]" type="hidden" value="<%%= activity.trackable.id %>">
            <input id="high_five_resource_type" name="high_five[resource_type]" type="hidden" value="Micro">
            <input id="high_five_user_id" name="high_five[user_id]" type="hidden" value="<%= current_user.id %>">
            <input class="small button tag" data-disable-with = "wait" name="commit" type="submit" value="high five!">
        </form>
        <%% } %>
        <% else %>
          <%= link_to "high five!", "#", :class => "reveal-signin-modal", :"data-alert-msg" => "Please join to High Five!" %>
        <% end %>
      </li>

      <li>
        <%= link_to "share", "", :class => "small button tag" %>
      </li>

      <li>
        <a href = "<%%= activity.trackable.url %>" class = "small button tag" >reply</a>
      </li>
    </ul>
  </div>
</div>

app/views/users/_social_link_fields.html.erb
<div class="fields nest-form"> 
<%= link_to_remove_fields "remove", f %>
<%= f.label :link, "Social Links" %>
<%= f.text_field :link %>
</div>

app/views/users/edit_profile.html.erb
<%= content_for :js do %>
<%= javascript_include_tag "jquery.tokeninput.js" %>
<script type="text/javascript">
$(function() {
	// $("#user_skill_list, .tokenize").tokenInput("/search_suggestions", {theme: "facebook"});
});
</script>

<% end %>
<%= content_for :head do %>
<%= stylesheet_link_tag "token-input.css" %>
<% end %>
<div class="twelve columns centered landing-container">
  <div class="row">
    <%= render "sidebar_dashboard" %>
		<%= render 'form_profile' %>
	</div>
</div>

app/views/users/followers.html.erb
<div class="twelve columns centered landing-container">
  <div class="row">
    <% if params[:username] %>
  		<%= render "users/sidebar_profile" %>
  	<% else %>
  		<%= render "sidebar_dashboard" %>
  	<% end %>
    <div class="six columns">
      <div class="row">
        <div class="twelve columns" id="feed-dashboard">
          <%= render :partial => "follower", :collection => @followers  %>
        </div>
      </div>
      <%= link_to "Load More", params[:username] ? user_followers_path(:page => 2) : followers_path(:page => 2), :remote => true, :disable_with => "Loading..", :id => "load_more_followers" %>
    </div>
    <div class="three columns">
    </div>
  </div>
</div>

app/views/users/goodies.js.erb
<% if @micros %>
	$("#mymicrosTab #feed-dashboard").append('<%= escape_javascript render(:partial => "micro", :collection => @micros, :locals => {:profile => true}) %>')
	<% if @micros.total_pages <= params[:page].to_i %>
		$("#mymicrosTab #load_more_feed").remove()
	<% else %>
		$("#mymicrosTab #load_more_feed").attr('href', '<%= goodies_path("micro", :page => (params[:page].to_i + 1 ), :username =>  @user.username ) %>')
	<% end %>
<% elsif @cards %>
	$("#mycardsTab #feed-dashboard").append('<%= escape_javascript render(:partial => "card", :collection => @cards, :locals => {:profile => true}) %>')
	<% if @cards.total_pages <= params[:page].to_i %>
		$("#mycardsTab #load_more_feed").remove()
	<% else %>
		$("#mycardsTab #load_more_feed").attr('href', '<%= goodies_path("card", :page => ( params[:page].to_i + 1), :username =>  @user.username ) %>')
	<% end %>
<% elsif @links %>
	$("#mylinksTab #feed-dashboard").append('<%= escape_javascript render(:partial => "link", :collection => @links, :locals => {:profile => true}) %>')
	<% if @cards.total_pages <= params[:page].to_i %>
		$("#mylinksTab #load_more_feed").remove();
	<% else %>
		$("#mylinksTab #load_more_feed").attr('href', '<%= goodies_path("link", :page => (params[:page].to_i + 1), :username =>  @user.username ) %>')
	<% end %>
<% end %>

app/views/users/update_company.html.erb
<div class="twelve columns centered landing-container">
  <div class="row">
    <%= render "users/sidebar_dashboard" %>
    <div class="six columns" style="padding-top: 26px;margin-bottom: 25px;">
      <%= render 'form_company' %>     
    </div>
    <div class="three columns">
    </div>
  </div>
</div>